### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by ljelinek-cznic** [helb/jidlobot#11]
Jidlobot prints this warning:

jidlobot.py:9: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(conf_file)

**Comment by helb** [comment]
thanks! :)
